ALTER PROCEDURE FGEN_SP_GENERACION_RESUMEN_EVALUACIONES_PENDIENTES
/********************************************************************************/  
/* Procedimiento: FGEN_SP_GENERACION_RESUMEN_EVALUACIONES_PENDIENTES	       	*/
/* Descripcion  : genera el resumen de las evaluaciones pendientes              */ 
/* Encargado    : John Jimenez 													*/  
/* Fecha y hora : 11/07/2012													*/ 
/* Version		: 1.0.0															*/ 
/********************************************************************************/ 
(
	@CH_CODIGO_COMPANIA				CHAR(3),
	@IN_CODIGO_EMPLEADO_NOTIFICAR	INT ,
	@VC_CORREO_EMPLEADO_NOTIFICAR	VARCHAR(64),	
	@NVCABECERAEXCEL				NVARCHAR(MAX),
	@CH_TIPO_NOTIFICACION			CHAR(02)	
)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @VC_FILE_TYPE								VARCHAR(5),
			@VC_SERVER_NAME								VARCHAR(50),
			@VC_DBNAME									VARCHAR(60),
			@VC_RUTA_ADJUNTO							VARCHAR(200),
			@VC_CONTENIDO_ADJUNTAR						VARCHAR(MAX),
			@SY_FOLDER_PATH								sysname,
			@VC_CONTENIDO_ARCHIVO						VARCHAR(MAX),
			@VC_QUERY									VARCHAR(4000),
			@RETURN										VARCHAR(10)
			
	DECLARE	@VC_TABLA_TEMPORAL_EV							VARCHAR(MAX),
			@VC_NOMBRE_ARCHIVO_ADJUNTO_EV					VARCHAR(250),
			@VC_NOMBRE_TABLA_TEMP_EV						VARCHAR(256),
			@VC_TABLA_TEMPORAL_JE							VARCHAR(MAX),
			@VC_NOMBRE_ARCHIVO_ADJUNTO_JE					VARCHAR(250),
			@VC_NOMBRE_TABLA_TEMP_JE						VARCHAR(256),
			@VC_NOMBRE_RESPONSABLE							VARCHAR(256)

	-- SETEAR VALORES
		SELECT	@VC_CONTENIDO_ADJUNTAR		=	'',
				@VC_SERVER_NAME				=	@@SERVERNAME,
				@VC_DBNAME					=	DB_NAME(),
				@VC_FILE_TYPE				=	'xls'
	
	--Obtenemos la Ubicación,donde se van generar los archivos excels para adjuntarse
	EXEC FEMP_SP_OBTENER_VALOR_PARAMETRO '083','09',@SY_FOLDER_PATH OUTPUT
	
	IF RIGHT(@SY_FOLDER_PATH,1) <> '\' SET @SY_FOLDER_PATH = @SY_FOLDER_PATH + '\'
	
	----Generamos el resumen
	IF @CH_TIPO_NOTIFICACION = 'EV'
	BEGIN
	
		--obtener el nombre del responsable
		SET @VC_NOMBRE_RESPONSABLE = (SELECT VC_NOMBRES + ' ' + VC_APELLIDO_PATERNO + ' ' + VC_APELLIDO_MATERNO FROM FPER_TA_EMPLEADO 
									  WHERE IN_CODIGO_EMPLEADO = @IN_CODIGO_EMPLEADO_NOTIFICAR)
		
		DECLARE @NVCABECERAEXCEL_CUR_EVALUADOR NVARCHAR(MAX)
		SET @NVCABECERAEXCEL_CUR_EVALUADOR  = @NVCABECERAEXCEL

		--SE COMENTA PARA CAMBIAR EL CONTENIDO DEL ADJUNTO

		--SET @NVCABECERAEXCEL_CUR_EVALUADOR = @NVCABECERAEXCEL_CUR_EVALUADOR +
		--	CAST ( (SELECT	td = ISNULL(VC_PERIODO,SPACE(1))				, '',
		--					td = ISNULL(VC_EVALUADO,SPACE(1))				, '',
		--					td = ISNULL(VC_NOMBRE_COMPROMISO,SPACE(1))		, '',
		--					td = ISNULL(VC_NOMBRE_ACCION,SPACE(1))			, '',
		--					td = ISNULL(CONVERT(VARCHAR(10),DT_FECHA_EVALUACION_PROGRAMADA,103),SPACE(1)) , ''
		--			FROM	#TEMPORAL_EVALUACIONES_PENDIENTES_EVALUADOR
		--	  FOR XML PATH('tr'), TYPE 
		--) AS NVARCHAR(MAX) )

		--SET @NVCABECERAEXCEL_CUR_EVALUADOR  = @NVCABECERAEXCEL_CUR_EVALUADOR + 
		--	N'</table>'	
			
		--SE COMENTA PARA CAMBIAR EL CONTENIDO DEL ADJUNTO	
			
		--Obtener el nombre del archivo adunto	
		SET	 @VC_NOMBRE_ARCHIVO_ADJUNTO_EV	 = 	'Notificacion-Evaluaciones-Pendientes-EV01'	
		
		--MODIFICACION CAMBIOS DE CONTENIDO---------------------------------------------------------------------------------------------
		--verificamos si existe la tabla TEMP_ARCHIVO_EV
		IF OBJECT_ID('TEMP_ARCHIVO') IS NOT NULL DROP TABLE TEMP_ARCHIVO
		--OR
		IF (OBJECT_ID('TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_EV,'-','_')) IS NOT NULL)
		BEGIN
			SET @VC_TABLA_TEMPORAL_EV = 'DROP TABLE TEMP_ARCHIVO_' +  REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_EV,'-','_')
			
			EXEC (@VC_TABLA_TEMPORAL_EV)
		END

		SET @VC_TABLA_TEMPORAL_EV =		'SELECT VC_PERIODO AS [PERIODO], 
				VC_EVALUADO AS [EVALUADO],
				VC_NOMBRE_COMPROMISO AS [NOMBRE COMPROMISO],
				VC_NOMBRE_ACCION AS [NOMBRE ACCION],
				CONVERT(VARCHAR(10),DT_FECHA_EVALUACION_PROGRAMADA,103) AS [FECHA EVALUACION PROGRAMADA] ' + 'INTO TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_EV,'-','_') + ' ' + '
				FROM	#TEMPORAL_EVALUACIONES_PENDIENTES_EVALUADOR'

		EXEC (@VC_TABLA_TEMPORAL_EV)


		--FIN OR	

		--MODIFICACION CAMBIOS DE CONTENIDO---------------------------------------------------------------------------------------------
			
		------llenamos la tabla TEMP_ARCHIVO_EV con la información que se va adjuntar en un archivo excel
		--SELECT VC_CONTENIDO_ARCHIVO = @NVCABECERAEXCEL_CUR_EVALUADOR INTO TEMP_ARCHIVO
		----OR
		--SET	@VC_TABLA_TEMPORAL_EV = ''
		--SET @VC_TABLA_TEMPORAL_EV = 'SELECT VC_CONTENIDO_ARCHIVO = ''' + @NVCABECERAEXCEL_CUR_EVALUADOR + ''' INTO TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_EV,'-','_')
		--EXEC (@VC_TABLA_TEMPORAL_EV)
		----FIN OR	
			
		--Generamos el archivo adjunto	
		--OR
		--SET @VC_CONTENIDO_ARCHIVO = N'SET NOCOUNT ON SELECT VC_CONTENIDO_ARCHIVO ' +  'FROM '+ 'TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_EV,'-','_')
		SET @VC_CONTENIDO_ARCHIVO = N'SET NOCOUNT ON SELECT * ' +  'FROM '+ 'TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_EV,'-','_')

		--PROCEDURE PARA INSERTAR MENSAJE CONTENIDO ADJUNTO		
		--PRINT 'GENERACION RESUMEN EVALUADOR'
		EXEC FGEN_SP_INSERTAR_TA_NOTIFICACION_EVALUACIONES_PENDIENTES	@CH_CODIGO_COMPANIA,@VC_CORREO_EMPLEADO_NOTIFICAR,@VC_CONTENIDO_ADJUNTAR,@VC_RUTA_ADJUNTO,'1',@VC_CONTENIDO_ARCHIVO,@VC_NOMBRE_ARCHIVO_ADJUNTO_EV,@VC_NOMBRE_RESPONSABLE,@CH_TIPO_NOTIFICACION

	END
	
	IF @CH_TIPO_NOTIFICACION = 'JE'
	BEGIN
		
		--obtener el nombre del responsable
		SET @VC_NOMBRE_RESPONSABLE = (SELECT VC_NOMBRES + ' ' + VC_APELLIDO_PATERNO + ' ' + VC_APELLIDO_MATERNO FROM FPER_TA_EMPLEADO 
									  WHERE IN_CODIGO_EMPLEADO = @IN_CODIGO_EMPLEADO_NOTIFICAR)
	
		DECLARE @NVCABECERAEXCEL_CUR_JEFE_EVALUADOR NVARCHAR(MAX)
		SET @NVCABECERAEXCEL_CUR_JEFE_EVALUADOR  = @NVCABECERAEXCEL

		--SE COMENTA PARA CAMBIAR EL CONTENIDO DEL ADJUNTO

		--SET @NVCABECERAEXCEL_CUR_JEFE_EVALUADOR = @NVCABECERAEXCEL_CUR_JEFE_EVALUADOR +
		--	CAST ( (SELECT	td = ISNULL(VC_PERIODO,SPACE(1))			, '',
		--					td = ISNULL(VC_EVALUADOR,SPACE(1))			, '',
		--					td = ISNULL(VC_EVALUADO,SPACE(1))			, '',
		--					td = ISNULL(VC_NOMBRE_COMPROMISO,SPACE(1))	, '',
		--					td = ISNULL(VC_NOMBRE_ACCION,SPACE(1))		, '',
		--					td = ISNULL(CONVERT(VARCHAR(10),DT_FECHA_EVALUACION_PROGRAMADA,103),SPACE(1)) , ''
		--			FROM	#TEMPORAL_EVALUACIONES_PENDIENTES_JEFE_EVALUADOR
		--	  FOR XML PATH('tr'), TYPE 
		--) AS NVARCHAR(MAX) )

		--SET @NVCABECERAEXCEL_CUR_JEFE_EVALUADOR  = @NVCABECERAEXCEL_CUR_JEFE_EVALUADOR + 
		--	N'</table>'	
			
		--SE COMENTA PARA CAMBIAR EL CONTENIDO DEL ADJUNTO	
			
		--Obtener el nombre del archivo adunto	
		SET	 @VC_NOMBRE_ARCHIVO_ADJUNTO_JE	 = 	'Notificacion-Evaluaciones-Pendientes-JE01'	
		
			--verificamos si existe la tabla TEMP_ARCHIVO_EV
		IF OBJECT_ID('TEMP_ARCHIVO') IS NOT NULL DROP TABLE TEMP_ARCHIVO
		--OR

		--MODIFICACION CAMBIOS DE CONTENIDO---------------------------------------------------------------------------------------------

		IF (OBJECT_ID('TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_JE,'-','_')) IS NOT NULL)
		BEGIN
			SET @VC_TABLA_TEMPORAL_JE = 'DROP TABLE TEMP_ARCHIVO_' +  REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_JE,'-','_')
			
			EXEC (@VC_TABLA_TEMPORAL_JE)
		END

		SET @VC_TABLA_TEMPORAL_JE =		'SELECT VC_PERIODO AS [PERIODO], 
			VC_EVALUADOR AS [EVALUADOR],
			VC_EVALUADO AS [EVALUADO],
			VC_NOMBRE_COMPROMISO AS [NOMBRE COMPROMISO],
			VC_NOMBRE_ACCION AS [NOMBRE ACCION],
			CONVERT(VARCHAR(10),DT_FECHA_EVALUACION_PROGRAMADA,103) AS [FECHA EVALUACION PROGRAMADA] ' + 'INTO TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_JE,'-','_') + ' ' + '
			FROM	#TEMPORAL_EVALUACIONES_PENDIENTES_JEFE_EVALUADOR'

		EXEC (@VC_TABLA_TEMPORAL_JE)

		--FIN OR
		
		--MODIFICACION CAMBIOS DE CONTENIDO---------------------------------------------------------------------------------------------		
			
		------llenamos la tabla TEMP_ARCHIVO con la información que se va adjuntar en un archivo excel
		--SELECT VC_CONTENIDO_ARCHIVO = @NVCABECERAEXCEL_CUR_JEFE_EVALUADOR INTO TEMP_ARCHIVO
		----OR
		--SET	@VC_TABLA_TEMPORAL_JE = ''
		--SET @VC_TABLA_TEMPORAL_JE = 'SELECT VC_CONTENIDO_ARCHIVO = ''' + @NVCABECERAEXCEL_CUR_JEFE_EVALUADOR + ''' INTO TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_JE,'-','_')
		--EXEC (@VC_TABLA_TEMPORAL_JE)
		----FIN OR	
			
		--Generamos el archivo adjunto	
		--OR
		--SET @VC_CONTENIDO_ARCHIVO = N'SET NOCOUNT ON SELECT VC_CONTENIDO_ARCHIVO ' +  'FROM '+ 'TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_JE,'-','_')
		SET @VC_CONTENIDO_ARCHIVO = N'SET NOCOUNT ON SELECT * ' +  'FROM '+ 'TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO_JE,'-','_')

		--PROCEDURE PARA INSERTAR MENSAJE CONTENIDO ADJUNTO
		--PRINT 'GENERACION RESUMEN JEFE EVALUADOR'
		EXEC FGEN_SP_INSERTAR_TA_NOTIFICACION_EVALUACIONES_PENDIENTES	@CH_CODIGO_COMPANIA,@VC_CORREO_EMPLEADO_NOTIFICAR,@VC_CONTENIDO_ADJUNTAR,@VC_RUTA_ADJUNTO,'1',@VC_CONTENIDO_ARCHIVO,@VC_NOMBRE_ARCHIVO_ADJUNTO_JE,@VC_NOMBRE_RESPONSABLE,@CH_TIPO_NOTIFICACION

	END		
END






