
ALTER PROCEDURE FGEN_SP_GENERACION_RESUMEN_DESVINCULACION_AUTOMATICA
/********************************************************************************/  
/* Procedimiento: FGEN_SP_GENERACION_RESUMEN_RENOVACIONES				       	*/
/* Descripcion  : 																*/ 
/* Encargado    : Oscar Ramos 												    */  
/* Fecha y hora : 2010.08.11													*/ 
/* Version		: 1.0.2															*/ 
/********************************************************************************/ 
(
	@CH_CODIGO_COMPANIA				CHAR(3),
	@IN_CODIGO_RESPONSABLE_UNIDAD	INT ,
	@IN_CODIGO_SEDE					INT,
	@VC_NOMBRE_AREA					VARCHAR(256),
	@VC_CORREO						VARCHAR(MAX),
	@NVCABECERARESUMEN				NVARCHAR(MAX),
	@NVCABECERAEXCEL				NVARCHAR(MAX),
	@IN_NUMERO_MENSAJE				INT
)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @IN_TOTAL_DIAS_VENCIDOS						INT,
			@IN_TOTAL_DIAS_VENCER_7						INT,
			@IN_TOTAL_DIAS_VENCER_30					INT,
			@IN_TOTAL_DIAS_VENCER_60					INT,
			@IN_TOTAL_DIAS_VENCER_90					INT,
			@IN_TOTAL									INT,
			@IN_CANTIDAD_DESVINCULACION					INT,
			@VC_FILE_TYPE								VARCHAR(5),
			@VC_SERVER_NAME								VARCHAR(50),
			@VC_DBNAME									VARCHAR(60),
			@VC_RUTA_ADJUNTO							VARCHAR(200),
			@VC_CONTENIDO_ADJUNTAR						VARCHAR(MAX),
			@SY_FOLDER_PATH								sysname,
			@VC_CONTENIDO_ARCHIVO						VARCHAR(MAX),
			@VC_QUERY									VARCHAR(4000),
			@RETURN										INT
			

	--OR
	DECLARE	@VC_TABLA_TEMPORAL							VARCHAR(MAX),
			@VC_NOMBRE_ARCHIVO_ADJUNTO					VARCHAR(250),
			@VC_NOMBRE_TABLA_TEMP						VARCHAR(256)
	--FIN OR

	-- SETEAR VALORES
		SELECT	@VC_CONTENIDO_ADJUNTAR		=	'',
				@VC_SERVER_NAME				=	@@SERVERNAME,
				@VC_DBNAME					=	DB_NAME(),
				@VC_FILE_TYPE				=	'xls'
	
	--Obtenemos la Ubicación,donde se van generar los archivos excels para adjuntarse
	EXEC FEMP_SP_OBTENER_VALOR_PARAMETRO '083','09',@SY_FOLDER_PATH OUTPUT
	
	IF RIGHT(@SY_FOLDER_PATH,1) <> '\' SET @SY_FOLDER_PATH = @SY_FOLDER_PATH + '\'
				
	--Obtenemos los totales de dias vencidos o por vencerse
	SELECT  @IN_TOTAL = COUNT(*)
	FROM	#TEMPORAL_EMPLEADOS_NOTIFICAR_DESVINCULACIONES_AUTOMATICAS
	WHERE	(@IN_CODIGO_RESPONSABLE_UNIDAD = 0 OR IN_CODIGO_RESPONSABLE_UNIDAD	=	@IN_CODIGO_RESPONSABLE_UNIDAD)
		AND	(@IN_CODIGO_SEDE = 0 OR IN_CODIGO_SEDE	=	@IN_CODIGO_SEDE)
	

	SET @IN_CANTIDAD_DESVINCULACION =	@IN_TOTAL	
	
	SET @IN_CANTIDAD_DESVINCULACION =  ISNULL(@IN_CANTIDAD_DESVINCULACION,0)
	
	IF @IN_CANTIDAD_DESVINCULACION <= 0 RETURN --Si no existe vencidas o por vencerse, no generar correo

	--Generamos la tabla resumen
	DECLARE @NVCABECERARESUMEN_CUR NVARCHAR(MAX)
	SET @NVCABECERARESUMEN_CUR = @NVCABECERARESUMEN

	IF @IN_CANTIDAD_DESVINCULACION>0 
	SET @NVCABECERARESUMEN_CUR = @NVCABECERARESUMEN_CUR +
		N'<tr align="center">' +
		N'<td>GENERADAS</td>' +
		N'<td>'+CAST(@IN_CANTIDAD_DESVINCULACION AS NVARCHAR(MAX))+'</td>' +
		N'</tr>'

	SET @NVCABECERARESUMEN_CUR = @NVCABECERARESUMEN_CUR + 
		N'</table>' 

	--Generamos el resumen
	DECLARE @NVCABECERAEXCEL_CUR NVARCHAR(MAX)
	SET @NVCABECERAEXCEL_CUR  = @NVCABECERAEXCEL

	--SE COMENTA PARA CAMBIAR EL CONTENIDO DEL ADJUNTO

	--SET @NVCABECERAEXCEL_CUR = @NVCABECERAEXCEL_CUR +
	--	CAST ( (SELECT	td = ISNULL(VC_CUC,SPACE(1))				, '',
	--					td = ISNULL(VC_COLABORADOR,SPACE(1))		, '',
	--					td = ISNULL(VC_NOMBRE_PUESTO,SPACE(1))	, '',
	--					td = ISNULL(VC_NOMBRE_AREA,SPACE(1))		, '',
	--					td = ISNULL(VC_NOMBRE_SEDE,SPACE(1))		, '',
	--					td = ISNULL(VC_NOMBRE_RESPONSABLE_UNIDAD,SPACE(1)) , '',
	--					td = ISNULL(CONVERT(VARCHAR(10),DT_FECHA_INGRESO,103),SPACE(1)) , '',
	--					td = ISNULL(CONVERT(VARCHAR(10),DT_FECHA_INICIO_CONTRATO,103),SPACE(1)) , '',
	--					td = ISNULL(CONVERT(VARCHAR(10),DT_FECHA_PROCESO,103),SPACE(1)) , ''
	--			FROM	#TEMPORAL_EMPLEADOS_NOTIFICAR_DESVINCULACIONES_AUTOMATICAS
	--			WHERE	(@IN_CODIGO_RESPONSABLE_UNIDAD = 0 OR IN_CODIGO_RESPONSABLE_UNIDAD	=	@IN_CODIGO_RESPONSABLE_UNIDAD)
	--				AND	(@IN_CODIGO_SEDE = 0 OR IN_CODIGO_SEDE	=	@IN_CODIGO_SEDE)
	--			ORDER	BY VC_COLABORADOR ASC
	--	  FOR XML PATH('tr'), TYPE 
	--) AS NVARCHAR(MAX) )

	--SET @NVCABECERAEXCEL_CUR  = @NVCABECERAEXCEL_CUR +
	--	N'</table>'

	--SE COMENTA PARA CAMBIAR EL CONTENIDO DEL ADJUNTO

	IF @IN_CODIGO_RESPONSABLE_UNIDAD > 0
	BEGIN
		--OR
		SET		@VC_NOMBRE_ARCHIVO_ADJUNTO	 = 'Desvinculacion-Unidad-'+ CONVERT(VARCHAR,@IN_CODIGO_RESPONSABLE_UNIDAD)+'-'+convert(varchar(8),getdate(),112)+'-'+CONVERT(VARCHAR,@IN_NUMERO_MENSAJE)
		--FIN OR
	END

	IF @IN_CODIGO_SEDE > 0 
	BEGIN
		--OR
		SET		@VC_NOMBRE_ARCHIVO_ADJUNTO	 = 'Desvinculacion-Admin-Desc-'+ CONVERT(VARCHAR,@IN_CODIGO_SEDE)+'-'+convert(varchar(8),getdate(),112)+'-'+CONVERT(VARCHAR,@IN_NUMERO_MENSAJE)
		--FIN OR
	END

	IF @IN_CODIGO_RESPONSABLE_UNIDAD = 0 AND @IN_CODIGO_SEDE = 0
	BEGIN
		--OR
		SET		@VC_NOMBRE_ARCHIVO_ADJUNTO	 = 'Desvinculacion-Admin-'+convert(varchar(8),getdate(),112)+'-'+CONVERT(VARCHAR,@IN_NUMERO_MENSAJE)
		--FIN OR
	END
	
	

	--verificamos si existe la tabla TEMP_ARCHIVO
	--OR
	IF (OBJECT_ID('TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO,'-','_')) IS NOT NULL)
	BEGIN
		SET @VC_TABLA_TEMPORAL = 'DROP TABLE TEMP_ARCHIVO_' +  REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO,'-','_')		
		EXEC (@VC_TABLA_TEMPORAL)
	END
	--MODIFICACION CAMBIOS DE CONTENIDO---------------------------------------------------------------------------------------------
	SET @VC_TABLA_TEMPORAL =		'SELECT VC_CUC AS [CUC], 
		VC_COLABORADOR AS [COLABORADOR],
		VC_NOMBRE_PUESTO AS [NOMBRE PUESTO],
		VC_NOMBRE_AREA AS [NOMBRE AREA],
		VC_NOMBRE_SEDE AS [NOMBRE SEDE],
		VC_NOMBRE_RESPONSABLE_UNIDAD AS [NOMBRE RESPONSABLE UNIDAD], 

		CONVERT(VARCHAR(10),DT_FECHA_INGRESO,103) AS [FECHA INGRESO],
		CONVERT(VARCHAR(10),DT_FECHA_INICIO_CONTRATO,103) AS [FECHA INICIO CONTRATO],
		CONVERT(VARCHAR(10),DT_FECHA_PROCESO,103) AS [FECHA PROCESO]' + 'INTO TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO,'-','_') + ' ' + '
		FROM	#TEMPORAL_EMPLEADOS_NOTIFICAR_DESVINCULACIONES_AUTOMATICAS
		WHERE	(' + CONVERT(VARCHAR(32),@IN_CODIGO_RESPONSABLE_UNIDAD) + ' = 0 OR IN_CODIGO_RESPONSABLE_UNIDAD	= ' + CONVERT(VARCHAR(32),@IN_CODIGO_RESPONSABLE_UNIDAD) + ') ' +
		' AND		(' + CONVERT(VARCHAR(32),@IN_CODIGO_SEDE) + ' = 0 OR IN_CODIGO_SEDE	= ' + CONVERT(VARCHAR(32),@IN_CODIGO_SEDE) + ') ' + 
		' ORDER	BY VC_COLABORADOR ASC'

	EXEC (@VC_TABLA_TEMPORAL)
	--MODIFICACION CAMBIOS DE CONTENIDO---------------------------------------------------------------------------------------------
	--FIN OR

	--llenamos la tabla TEMP_ARCHIVO con la información que se va adjuntar en un archivo excel
	--OR
	--SET	@VC_TABLA_TEMPORAL = ''
	--SET @VC_TABLA_TEMPORAL = 'SELECT VC_CONTENIDO_ARCHIVO = ''' + @NVCABECERAEXCEL_CUR + ''' INTO TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO,'-','_')
	--EXEC (@VC_TABLA_TEMPORAL)
	--FIN OR
	
	--Generamos el archivo adjunto	
	--OR
	SET @VC_CONTENIDO_ARCHIVO = N'SET NOCOUNT ON SELECT * ' +  'FROM '+ 'TEMP_ARCHIVO_' + REPLACE(@VC_NOMBRE_ARCHIVO_ADJUNTO,'-','_')
	
	--PROCEDURE PARA INSERTAR MENSAJE CONTENIDO ADJUNTO
	EXEC FGEN_SP_INSERTAR_TA_NOTIFICACION_DESVINCULACION_AUTOMATICA	@CH_CODIGO_COMPANIA,@VC_CORREO,@NVCABECERARESUMEN_CUR,@VC_CONTENIDO_ADJUNTAR,@VC_RUTA_ADJUNTO,@VC_NOMBRE_AREA,@IN_CANTIDAD_DESVINCULACION,'1',@VC_CONTENIDO_ARCHIVO,@VC_NOMBRE_ARCHIVO_ADJUNTO


	
END

